baseURL = 'https://renandotcorrea.github.io/'
languageCode = 'en-us'
title = 'Renan de Andrade Correa'
theme = 'hugo-profile'
[params]
	favicon = "/favi.png"
	[params.navbar]
		brandName = "renandotcorrea"
		disableSearch = true
		brandLogo = "/logo-white.png"
	[params.hero]
		enable = true
		intro = "Hi, my name is"
		title = "Renan de Andrade Correa."
		subtitle = "I'm a Backend Developer."
		content = "I'm a experienced professional with a passion for building scalable and efficient web applications. I love working with modern technologies and continuously improving my skills."
		image = "/1755525446765-min.jpg"
		[params.hero.bottomImage]
			enable = true
		 	roundImage = true # Make hero image circular | default false
		[params.hero.button]
			enable = true
			name = "Resume"
			url = "https://drive.google.com/file/d/1rTxF9k3lYieOVUx5DGefERIjboPm-J7n/view?usp=sharing"
			download = true
			newPage = true
		[params.hero.socialLinks]
			[[params.hero.socialLinks.fontAwesomeIcons]]
			icon = "fab fa-github"
			url = "https://github.com/renandotcorrea"
			[[params.hero.socialLinks.fontAwesomeIcons]]
			icon = "fab fa-linkedin"
			url = "https://www.linkedin.com/in/renandotcorrea/"
	[params.about]
		enable = true
		title = "About Me"
		content = "I'm a Backend Developer with expertise in building robust and scalable web applications. I have a strong background in various programming languages and frameworks, and I'm passionate about learning new technologies and improving my skills. In my free time, I like to write technical articles and read good books.\n\n I am currently working as a software developer at Globo."
		image = "/1639433955520.jpeg"
	[params.footer]
		enable = true
		[params.footer.socialNetworks]
			github = "https://github.com/renandotcorrea"
			linkedin = "https://www.linkedin.com/in/renandotcorrea/"
			instagram = "https://www.instagram.com/renandotcorrea/"
[caches]
[caches.images]
dir = ':cacheDir/images'
